language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
before_install:
  - python --version
  - pip install codecov
install:
  - pip install coverage pytest-cov pytest
  - pip install -r requirements.txt
script: pytest --cov=./
after_success: codecov