language: python
python:
  - "3.7"
before_install:
  - wget https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.1-linux-x86_64.tar.gz
  - tar zxvf julia-1.3.1-linux-x86_64.tar.gz
  - export PATH="$PATH:/julia-1.3.1-linux-x86_64/bin"
  - julia pomato/_installation/julia_install_from_git.jl
  - python --version
  - pip install codecov

install:
  - pip install coverage pytest-cov 
  - pip install pytest==4.6
  - pip install -r requirements.txt
script: pytest --cov=./
after_success: codecov