language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
before_install:
  - python --version
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install pytest coverage
  - pip install pytest-cov==2.6.0
script: pytest --cov=./
after_success: codecov