language: python
os:
  - linux
python:
  - "3.7"
before_install:
  - chmod +x tests/install_julia.sh
  - ./tests/install_julia.sh
  - python --version
  - julia --version
  - julia pomato/_installation/julia_install_from_git.jl
  - pip install codecov

install:
  - pip install coverage pytest-cov 
  - pip install pytest==4.6
  - pip install -r requirements.txt

script: pytest --cov=./
after_success: codecov